# Cargo audit configuration
[advisories]
# Ignore unmaintained warning for paste crate as it's a transitive dependency
# from rmcp and poses no security risk as a simple procedural macro
ignore = [
    "RUSTSEC-2024-0436"  # paste crate unmaintained warning
]

# Configure informational warnings (optional)
informational_warnings = ["unmaintained", "unsound", "notice"]
